CREATE TABLE evt_type (
    id INTEGER PRIMARY KEY NOT NULL,
    name VARCHAR NOT NULL UNIQUE
);

CREATE TABLE events (
    id INTEGER PRIMARY KEY NOT NULL,
    evt_type INTEGER NOT NULL REFERENCES evt_type(id),
    timestamp DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    message TEXT NOT NULL DEFAULT ''
);
