[package]
name = "worklog"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
chrono = "0.4.19"
chrono-english = "0.1.7"
color-eyre = "0.6.1"
diesel = { version = "1.4.8", features = ["sqlite", "chrono"] }
diesel_migrations = "1.4.0"
dirs = "4.0.0"
lalrpop-util = "0.19.8"
regex = "1.5.6"
supports-hyperlinks = "1.2.0"
terminal-link = "0.1.0"
thiserror = "1.0.31"

[build-dependencies]
lalrpop = "0.19.8"
